export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const PROFILE_FEATCHED = 'PROFILE_FEATCHED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const EXPENSE_SAVED = 'EXPENSE_SAVED';
export const EXPENSE_UPDATED = 'EXPENSE_UPDATED';
export const RESET_SAVED_FLAG = 'RESET_SAVED_FLAG';

export const FETCHING_EXPENSE = 'FETCHING_EXPENSE';
export const FETCHED_SUCCESS = 'FETCHED_SUCCESS';
export const FETCHED_FAILED = 'FETCHED_FAILED';

export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
